[tool.poetry]
name = "bandcamp-wishlist"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.12.2"
requests = "^2.27.1"
browser-cookie3 = "^0.14.0"
dateparser = "^1.2.0"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.7"

